### ISSUE TITLE
关于聊天室

### ISSUE THREAD

**Issue by liuhaoranA** [whileskies/curriculum_design#13]
你好，因为刚接触项目还不太了解要如何运行这种linux环境下的项目，想问一下聊天室要在虚拟机里运行吗，如何运行呢

**Comment by whileskies** [comment]
linux环境可以用虚拟机，也可以用windows的wsl，运行的话详见[README](https://github.com/whileskies/curriculum_design/tree/master/SoftwareArchitecture)

**Comment by liuhaoranA** [comment]
感谢！!可是我在安装libevent后，编译AccessClient的过程中有报错，警告暂时没管，报错如下：
access/AccessClient.cpp:25:28: 错误：‘SOL_TCP’在此作用域中尚未声明
         setsockopt(sockfd, SOL_TCP, TCP_KEEPIDLE, (void*)&keepIdle, sizeof(keepIdle));
                            ^
access/AccessClient.cpp:25:37: 错误：‘TCP_KEEPIDLE’在此作用域中尚未声明
         setsockopt(sockfd, SOL_TCP, TCP_KEEPIDLE, (void*)&keepIdle, sizeof(keepIdle));
                                     ^
access/AccessClient.cpp:26:37: 错误：‘TCP_KEEPINTVL’在此作用域中尚未声明
         setsockopt(sockfd, SOL_TCP, TCP_KEEPINTVL, (void *)&keepInterval, sizeof(keepInterval));
                                     ^
access/AccessClient.cpp:27:37: 错误：‘TCP_KEEPCNT’在此作用域中尚未声明
         setsockopt(sockfd, SOL_TCP, TCP_KEEPCNT, (void *)&keepCount, sizeof(keepCount));

我想先把它运行起来，再进一步学习涉及到的知识点，求大佬指点（可以留个邮箱或者加个好友进一步交流吗orz）

**Comment by whileskies** [comment]
这个我更新过了，[fix bug](https://github.com/whileskies/curriculum_design/commit/0cfe986fb69430f1b989b2922bbe792b76e4b748)
qq:1103952501
